name: 📄 Documentation issue
description: Is there an issue in the documentation?
title: "[DOCS]: "
labels: ["documentation"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time for notice and file a report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A breif description of what is wrong
      placeholder: Tell us what is wrong
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please include a screenshot if needed
    validations:
      required: true
  - type: textarea
    id: additonal-info
    attributes:
      label: Additional inforamtion
      description: Is there anything we should know about
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        You can also join our Discord channel [here]("expired.html")
