name: ✨ Feature Request
description: File a bug report
title: "[Feature]: "
labels: ["✨features", "🛸addition"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the feature you need to be added
      placeholder: Start journey here
    validations:
      required: true
  - type: file
    id: screenshots
    attributes:
      label: Screenshost
      description: You can start by sharing an image or a video describing the feature
      placeholder: Start journey here
    validations:
      required: true
 - type: textarea
    id: info
    attributes:
      label: Info
      description: Share any additional information concering this feature
      placeholder: Addition information
    validations:
      required: true
- type: markdown
    attributes:
      value: |
        You can also check out our discord channel [here]("https://example.com")
