name: ✨ Feature Request
description: File a bug report
title: "[Feature]: "
labels: ["✨features", "🛸addition"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the feature you need to be added
      placeholder: Start journey here
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshost
      description: You can start by sharing an image or a video describing the feature
      placeholder: Start journey here
    validations:
      required: true
   - type: textarea
     id: what-happened
     attributes:
       label: What happened?
       description: Also tell us, what did you expect to happen?
       placeholder: Tell us what you see!
       value: "A bug happened!"
     validations:
      required: true
